export const SET_COVID_STATS = 'SET_COVID_STATS'
export const SET_COUNTRIES = 'SET_COUNTRIES'
export const SET_COUNTRY = 'SET_COUNTRY'
export const SET_COUNTRIES_STATS = 'SET_COUNTRIES_STATS'
export const SET_IS_FETCHING_COVID_STATS = 'SET_IS_FETCHING_COVID_STATS'
export const SET_IS_FETCHING_COUNTRIES_STATS = 'SET_IS_FETCHING_COUNTRIES_STATS'

